# Generated by Django 5.1.2 on 2024-11-17 20:59

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flashcards', '0005_rating'),
    ]

    operations = [
        migrations.RenameField(
            model_name='rating',
            old_name='stars',
            new_name='rating',
        ),
        migrations.AlterUniqueTogether(
            name='rating',
            unique_together={('flashcard', 'user')},
        ),
        migrations.AlterField(
            model_name='rating',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.RemoveField(
            model_name='rating',
            name='created_at',
        ),
    ]
