# Generated by Django 5.1.2 on 2024-11-25 10:56

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flashcards', '0010_telemetry'),
    ]

    operations = [
        migrations.AlterField(
            model_name='telemetry',
            name='end_time',
            field=models.DateTimeField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='telemetry',
            name='flashcard',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='flashcards.flashcard'),
        ),
        migrations.AlterField(
            model_name='telemetry',
            name='start_time',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='telemetry',
            name='success',
            field=models.BooleanField(),
        ),
    ]
