# Generated by Django 5.1.2 on 2024-11-25 11:24

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flashcards', '0011_alter_telemetry_end_time_alter_telemetry_flashcard_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='telemetry',
            name='end_time',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='telemetry',
            name='start_time',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='telemetry',
            name='success',
            field=models.BooleanField(default=False),
        ),
    ]
