# Generated by Django 5.1.2 on 2024-11-25 14:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flashcards', '0012_alter_telemetry_end_time_alter_telemetry_start_time_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='telemetry',
            name='start_time',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='telemetry',
            name='success',
            field=models.BooleanField(),
        ),
    ]
