"""
Django settings for testvar project.

Generated by 'django-admin startproject' using Django 5.1.1.

For more information on this file, see
https://docs.djangoproject.com/en/5.1/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.1/ref/settings/
"""

from pathlib import Path
import os

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'django-insecure-nje&+x9@ut_s_7g^+6(0k7fig=11le!tmtc#$g9v-y18unb2%s'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = False

ALLOWED_HOSTS = ["testvar-production.up.railway.app", "127.0.0.1", "localhost"]

# Application definition
INSTALLED_APPS = [
    'flashcards',  
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'rest_framework',
    'drf_spectacular',  
    'drf_spectacular_sidecar',  
]

REST_FRAMEWORK = {
    'DEFAULT_AUTHENTICATION_CLASSES': [
        'rest_framework.authentication.SessionAuthentication',
        'rest_framework.authentication.BasicAuthentication',
    ],
    'DEFAULT_PERMISSION_CLASSES': [
        'rest_framework.permissions.AllowAny',
    ],
    'DEFAULT_SCHEMA_CLASS': 'drf_spectacular.openapi.AutoSchema',
}

# Custom User Model
AUTH_USER_MODEL = 'flashcards.User'

# Redirects after login/logout
LOGIN_REDIRECT_URL = '/'  
LOGOUT_REDIRECT_URL = '/login/' 

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'testvar.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'testvar.wsgi.application'

# Database
DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': BASE_DIR / 'db.sqlite3',
    }
}

# Password validation
AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]

# Internationalization
LANGUAGE_CODE = 'en-us'
TIME_ZONE = 'UTC'
USE_I18N = True
USE_TZ = True



# Archivos estáticos (CSS, JS, imágenes)
STATIC_URL = "/static/"
STATIC_ROOT = os.path.join(BASE_DIR, "staticfiles")  # Carpeta donde Django guardará los archivos
STATICFILES_DIRS = [os.path.join(BASE_DIR, "static")]  # Carpeta donde están los archivos en desarrollo

# Default primary key field type
DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

# DRF Spectacular settings
SPECTACULAR_SETTINGS = {
    'TITLE': 'TestVar - Flashcards API',
    'DESCRIPTION': 'A revolutionary REST API for flashcards',
    'VERSION': '1.0.0',
    'SERVE_INCLUDE_SCHEMA': True,
    'SERVERS': [
        {'url': 'http://localhost:8000/api', 'description': 'Development server'},
        {'url': 'http://testvar.difcsi.hu/api', 'description': 'Reference server'},
    ],
    'SCHEMA_PATH_PREFIX': '/api/',
}

LOGIN_URL = '/login/' 


AUTH_USER_MODEL = 'flashcards.User'


STATIC_ROOT = BASE_DIR / "staticfiles"

CSRF_TRUSTED_ORIGINS = [
    "https://testvar-production.up.railway.app"
]
CSRF_COOKIE_SECURE = True  # Asegura que la cookie CSRF se envía solo por HTTPS
CSRF_COOKIE_HTTPONLY = False  # Evita que los scripts del navegador accedan a la cookie
CSRF_USE_SESSIONS = True  # Usa la sesión para almacenar el token CSRF
